base: &base
  secret_key_base: '<set key>'

production:
  <<: *base
  basic_auth:
    username: '<set username>'
    password: '<set password>'
  airbrake:
    api_key: ''

development:
  <<: *base
  facebook:
    key: '<set key>'
    secret: '<set secret>'
  basic_auth:
    username: '<set username>'
    password: '<set password'

test: *base
